### PR TITLE
closes #675 ensure that the date at the selected index matches the da…

### LINKED ISSUE #675: Day text incorrect for graph

### PR DESCRIPTION
**Pull request by finger563**
…te of the object - prevent records older than the past week from showing up at the beginning of the week due to usage of "closestIndexTo" which returns 0 even if the dates do not match exactly.

### CODE REVIEW

File: apps/wear/smartdrive/app/pages/main-page/main-view-model.ts [hunk 1]
```diff
@@ -2478,16 +2478,17 @@ export class MainViewModel extends Observable {
           const obj = SmartDriveData.Info.loadInfo(...o);
           const objDate = new Date(obj.date);
           const index = closestIndexTo(objDate, dates);
-          // const usageDate = dates[index];
-          if (index > -1) {
+          const usageDate = dates[index];
```
Comment (p-ranav) [inline apps/wear/smartdrive/app/pages/main-page/main-view-model.ts]: Probably need to check here if `index > -1` instead of two lines later. 

```typescript
x = [1, 2, 3]
y = x[-1]
```

will cause `y` to be `undefined`
