### PR TITLE
closes #818

### LINKED ISSUE #818: Bug: logging exception when permissions prompt times out/screen turns off
Sentry Issue: [SMARTDRIVE-WEAROS-93](https://sentry.io/organizations/maxmobility/issues/1579468943/?referrer=github_integration)

```
Throwable: None
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
...
(16 additional frame(s) were not displayed)

Exception: None
    at com.permobil.smartdrive.wearos.MainActivity.onRequestPermissionsResult(MainActivity.java:72)
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by bradmartin**
Uses an explicit catch on the permissions prompt action so we just log a breadcrumb if that fails now. Since the app won't crash at this point the breadcrumb should be sufficient for our use.

### CODE REVIEW

File: apps/wear/smartdrive/app/pages/main-page/main-view-model.ts [hunk 1]
```diff
@@ -859,7 +885,14 @@ export class MainViewModel extends Observable {
...
+        // using explicit .catch here because we don't need to log the exception in this case
+        // the user didn't allow permission or the screen went off/activity changed while the OS
+        // prompt was waiting for user to grant permissions.
+        await requestPermissions(neededPermissions, () => {}).catch(err => {
+          sentryBreadCrumb(
+            `Request Permissions was not granted ${JSON.stringify(err)}`
+          );
+        });
         // now that we have permissions go ahead and save the serial number
         this._updateSerialNumber();
```
Comment (finger563) [inline apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:897]: Won't this line fail if we're not throwing an exception - the user didn't grant permissions yet we try to access the serial number which requires permissions

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:897]: ah crap, yea so we need to return out of it in the catch... good thinking, because I didn't test that 🤦 I'll update it so we skip over the rest.

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: ah so you actually meant it will fail if they don't, so we were ending up in the `catch()` of the `try/catch` on that method call. So now it ends up in the `.catch()` off the awaited call when the activity is stopped. Because the `requestPermissions` method does error if the user doesn't grant permissions. So when the activity is stopped those prompts end up dismissed and we end up with the error.

That's why it seemed the explicit `.catch()` there would let us just capture the breadcrumb for when the requestPermissions fails since we don't really care if it fails, we always have the check for permissions prior to doing bluetooth work so this should be fine...

Does that make sense or not tho 🙃

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: I may have even confused myself more explaining that but going back to original reason I think this should be correct. We're `await`ing the permissions prompt, in the case the user declines or activity is stopped (app backgrounded) it will end up throwing and we end up in the `.catch()` on the method so returning out should prevent execution from anything after the awaited method errors.

Comment (finger563) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: does the `return false` return from the containing function or is it just the return value of `await requestPermissions(...).catch(...);`? I believe it's just the return value of the await, which isn't being used, but i'm not sure

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: yea let me check that real quick...

Comment (finger563) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: if I understand correctly it should be:
```ts
const gotPermissions = await requestPermissions(neededPermissions, () =>{}).then(() => {
    this._updateSerialNumber();
    return true;
}).catch(err => {
    sentryBreadCrumb(
            `Request Permissions was not granted ${JSON.stringify(err)}`
     );
    return false;
});
```

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: yea you're right, so it still hits it... maybe that's why I actually changed all of this to a `try/catch` during the last release, because we were using more explicit `catch` on the promise methods.

Comment (bradmartin) [reply apps/wear/smartdrive/app/pages/main-page/main-view-model.ts:898]: yep that's it, good catch, becuase I def. was not testing that scenario 🙃  I just wanted to fix that stupid exception from logging
